using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Network;
using Server.Targeting;
using Server.AIOrchestrator.Factions;

namespace Server.AIOrchestrator
{
    #region Data Types

    public enum QuestObjectiveType
    {
        KillCount,      // Kill X of creature type Y
        CollectItem,    // Bring X of item Y to quest giver
        DeliverItem,    // Take item Y to NPC Z
        Escort,         // Escort NPC Z to location
        Explore,        // Visit location Y
        CombatBoss,     // Kill a named boss/strong creature
        MerchantRun,    // Buy X items and bring them (trade route)
        CraftItem,      // Craft X of specific item type
        NpcRelation,    // Build reputation with another NPC (talk to them multiple times)
        GuardDuty,      // Defend a location from attackers
        Rescue,         // Rescue a captured NPC from a dungeon
        Scout,          // Scout a dangerous area and report back
        GatherResource, // Mine/chop/fish X amount of a resource
        Bounty          // Kill a specific named creature (bounty)
    }

    public class AIQuest
    {
        public string QuestId { get; set; } = Guid.NewGuid().ToString("N").Substring(0, 8);
        public string GiverNpcName { get; set; }
        public string QuestTitle { get; set; }
        public string QuestDescription { get; set; }
        public QuestObjectiveType ObjectiveType { get; set; }
        public string ObjectiveTarget { get; set; }     // creature type / item name / NPC name / location name
        public int ObjectiveCount { get; set; } = 1;
        public int ObjectiveProgress { get; set; } = 0;
        public string RewardDescription { get; set; }
        public int RewardGold { get; set; } = 100;
        public DateTime IssuedAt { get; set; } = DateTime.UtcNow;
        public DateTime ExpiresAt { get; set; } = DateTime.UtcNow.AddHours(4);
        public bool IsCompleted { get; set; }
        public bool IsExpired => DateTime.UtcNow > ExpiresAt;
        public string PlayerSerial { get; set; }
        public string GiverSerial { get; set; }

        // For DeliverItem/Escort/Explore
        public string SecondaryTarget { get; set; }    // destination NPC name / location name
        public Point3D Destination { get; set; }        // for Escort/Explore
        public Map DestinationMap { get; set; }
        public Item QuestItem { get; set; }             // for DeliverItem - the item to deliver
        public Serial EscortNpcSerial { get; set; }     // serial of escort NPC
    }

    #endregion

    /// <summary>
    /// Manages AI-generated quests: creation, tracking, completion.
    /// Quests are generated by LLM when a player asks an NPC for work.
    /// </summary>
    public static class AIQuestManager
    {
        private static readonly Dictionary<string, AIQuest> ActiveQuests = new Dictionary<string, AIQuest>();
        private static readonly List<string> CompletedQuestIds = new List<string>();

        private static readonly string[] CreatureNames = {
            "rat", "orc", "lizardman", "snake", "giant spider", "wolf",
            "goblin", "troll", "ettin", "lich", "skeleton", "zombie",
            "ghoul", "wraith", "daemon", "dragon", "wyvern", "imp",
            "gargoyle", "ogre", "stone harpy", "mummy", "spectre",
            "headless", "gazer", "mongbat", "slime", "earth elemental",
            "air elemental", "fire elemental", "water elemental", "poison elemental",
            "orc lord", "drake", "nightmare", "pixie", "centaur"
        };

        // Boss-level creatures for CombatBoss quests
        private static readonly string[] BossNames = {
            "Barracoon the Piper", "Lord Oaks", "Mephitis", "Rikktor", "Semonath",
            "Neira the Necromancer", "The Exodus", "Dragon of Trinsic", "The Shadowlord",
            "The Ancient Wyrm", "The Balron of Destard", "The Titan of Fire", "The Kraken",
            "The Serpentine Dragon", "The Daemon Prince", "The Lich King", "The Plague Lord"
        };

        private static readonly string[] ItemNames = {
            "bones", "skulls", "gems", "ingots", "boards", "leather",
            "spider silk", "bat wings", "nightshade", "garlic", "ginseng",
            "iron ore", "gold ore", "silver", "rubies", "sapphires",
            "emeralds", "diamonds", "scrolls", "potions",
            "bolts of cloth", "hides", "feathers", "shafts", "arrows",
            "reagents", "crystal shards", "magical residue", "enchanting dust"
        };

        // Items that the player must purchase for MerchantRun quests
        private static readonly string[] TradeItems = {
            "bolt of cloth", "bottle of wine", "barrel of ale", "silk robe",
            "spices", "jewelry", "fine glassware", "exotic fur",
            "rare herbs", "magical scrolls", "mithril ingots", "diamond dust"
        };

        // Items players need to craft for CraftItem quests
        private static readonly string[] CraftableItems = {
            "leather armor", "chainmail coif", "broadsword", "healing potion",
            "wooden shield", "magic wand", "studded gloves", "longbow",
            "ringmail tunic", "battle axe", "kryss", "plate helm"
        };

        private static readonly string[] DeliveryNpcNames = {
            "the town crier", "the blacksmith", "the healer", "the innkeeper",
            "the banker", "the stable master", "the provisioner", "the tinker",
            "the shipwright", "the alchemist", "the scribe", "the mayor",
            "the mage", "the ranger", "the paladin", "the farmer"
        };

        // NPCs that players need to talk to for NpcRelation quests
        private static readonly string[] NpcRelationTargets = {
            "the blacksmith of Britain", "the healer of Trinsic", "the innkeeper of Vesper",
            "the mage of Moonglow", "the ranger of Yew", "the paladin of Trinsic",
            "the bard of Skara Brae", "the fisherman of Serpent's Hold",
            "the miner of Minoc", "the tinker of Nujel'm"
        };

        private static readonly string[] LocationNames = {
            "the graveyard", "the old lighthouse", "the abandoned mine", "the druid grove",
            "the pirate cave", "the ancient ruins", "the waterfall", "the mountain pass",
            "the dark forest clearing", "the shipwreck", "the standing stones", "the wizard tower",
            "the dragon's den", "the crypt of the damned", "the frozen tundra", "the volcanic crater"
        };

        // Guard Duty / Scout locations
        private static readonly string[] GuardLocations = {
            "the north gate", "the south road", "the east bridge", "the west tower",
            "the town square", "the marketplace", "the docks", "the graveyard gate"
        };

        // Resource types for GatherResource quests
        private static readonly string[] ResourceTypes = {
            "iron ore", "logs", "fish", "grain", "stone blocks",
            "gold ore", "gems", "hides", "cotton", "flax"
        };

        public static void Initialize()
        {
            // Cleanup expired quests every 5 minutes
            Timer.DelayCall(TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5), CleanupExpired);
            Console.WriteLine("[AIOrchestrator] Quest system initialized.");
        }

        /// <summary>Is the player eligible for a new quest from this NPC?</summary>
        public static bool CanGiveQuest(Mobile player, BaseCreature npc)
        {
            if (player == null || npc == null) return false;

            var playerSer = player.Serial.Value.ToString();
            // Check if player already has an active quest from this NPC
            return !ActiveQuests.Values.Any(q =>
                q.PlayerSerial == playerSer &&
                q.GiverSerial == npc.Serial.Value.ToString() &&
                !q.IsCompleted && !q.IsExpired);
        }

        /// <summary>Generate a new quest using LLM.</summary>
        public static async Task<AIQuest> GenerateQuest(Mobile player, BaseCreature npc)
        {
            var playerSer = player.Serial.Value.ToString();
            var npcSer = npc.Serial.Value.ToString();

            // Pick a random objective type (expanded weights)
            var weights = new[] { 15, 10, 8, 5, 4, 8, 8, 8, 7, 7, 5, 8, 7 };
            // KillCount, Collect, Deliver, Escort, Explore, CombatBoss, MerchantRun,
            // CraftItem, NpcRelation, GuardDuty, Rescue, Scout, GatherResource, Bounty
            var total = weights.Sum();
            var roll = Utility.Random(total);
            var cumulative = 0;
            var objectiveType = QuestObjectiveType.KillCount;
            for (int i = 0; i < weights.Length; i++)
            {
                cumulative += weights[i];
                if (roll < cumulative)
                {
                    objectiveType = (QuestObjectiveType)i;
                    break;
                }
            }

            string target = "";
            string secondary = "";
            int count = 1;
            int goldReward = 100;
            Point3D dest = Point3D.Zero;
            Map destMap = Map.Felucca;

            switch (objectiveType)
            {
                case QuestObjectiveType.KillCount:
                    target = CreatureNames[Utility.Random(CreatureNames.Length)];
                    count = Utility.RandomMinMax(3, 12);
                    goldReward = count * Utility.RandomMinMax(25, 60);
                    break;

                case QuestObjectiveType.CollectItem:
                    target = ItemNames[Utility.Random(ItemNames.Length)];
                    count = Utility.RandomMinMax(3, 15);
                    goldReward = count * Utility.RandomMinMax(15, 40);
                    break;

                case QuestObjectiveType.DeliverItem:
                    target = ItemNames[Utility.Random(ItemNames.Length)];
                    secondary = DeliveryNpcNames[Utility.Random(DeliveryNpcNames.Length)];
                    count = Utility.RandomMinMax(1, 5);
                    goldReward = count * Utility.RandomMinMax(30, 80);
                    break;

                case QuestObjectiveType.Escort:
                    target = "a traveler";
                    secondary = LocationNames[Utility.Random(LocationNames.Length)];
                    count = 1;
                    goldReward = Utility.RandomMinMax(200, 500);
                    dest = new Point3D(npc.X + Utility.RandomMinMax(-20, 20),
                                       npc.Y + Utility.RandomMinMax(-20, 20), npc.Z);
                    destMap = npc.Map;
                    break;

                case QuestObjectiveType.Explore:
                    target = LocationNames[Utility.Random(LocationNames.Length)];
                    secondary = "";
                    count = 1;
                    goldReward = Utility.RandomMinMax(150, 400);
                    dest = new Point3D(npc.X + Utility.RandomMinMax(-30, 30),
                                       npc.Y + Utility.RandomMinMax(-30, 30), npc.Z);
                    destMap = npc.Map;
                    break;

                case QuestObjectiveType.CombatBoss:
                    target = BossNames[Utility.Random(BossNames.Length)];
                    count = 1;
                    goldReward = Utility.RandomMinMax(500, 2000);
                    break;

                case QuestObjectiveType.MerchantRun:
                    target = TradeItems[Utility.Random(TradeItems.Length)];
                    secondary = DeliveryNpcNames[Utility.Random(DeliveryNpcNames.Length)];
                    count = Utility.RandomMinMax(1, 5);
                    goldReward = count * Utility.RandomMinMax(50, 120);
                    break;

                case QuestObjectiveType.CraftItem:
                    target = CraftableItems[Utility.Random(CraftableItems.Length)];
                    count = Utility.RandomMinMax(1, 5);
                    goldReward = count * Utility.RandomMinMax(60, 150);
                    break;

                case QuestObjectiveType.NpcRelation:
                    target = NpcRelationTargets[Utility.Random(NpcRelationTargets.Length)];
                    count = Utility.RandomMinMax(2, 5); // Number of conversations
                    goldReward = count * Utility.RandomMinMax(20, 40);
                    break;

                case QuestObjectiveType.GuardDuty:
                    target = GuardLocations[Utility.Random(GuardLocations.Length)];
                    count = Utility.RandomMinMax(3, 8); // Number of waves
                    goldReward = Utility.RandomMinMax(200, 600);
                    dest = new Point3D(npc.X + Utility.RandomMinMax(-10, 10),
                                       npc.Y + Utility.RandomMinMax(-10, 10), npc.Z);
                    destMap = npc.Map;
                    break;

                case QuestObjectiveType.Rescue:
                    target = "a captured citizen";
                    secondary = LocationNames[Utility.Random(LocationNames.Length)];
                    count = 1;
                    goldReward = Utility.RandomMinMax(300, 800);
                    break;

                case QuestObjectiveType.Scout:
                    target = LocationNames[Utility.Random(LocationNames.Length)];
                    count = 1;
                    goldReward = Utility.RandomMinMax(100, 300);
                    break;

                case QuestObjectiveType.GatherResource:
                    target = ResourceTypes[Utility.Random(ResourceTypes.Length)];
                    count = Utility.RandomMinMax(10, 50);
                    goldReward = count * Utility.RandomMinMax(3, 8);
                    break;

                case QuestObjectiveType.Bounty:
                    target = BossNames[Utility.Random(BossNames.Length)];
                    count = 1;
                    goldReward = Utility.RandomMinMax(800, 3000);
                    break;
            }

            var quest = new AIQuest
            {
                GiverNpcName = npc.Name ?? "the NPC",
                QuestTitle = $"Help the {npc.Name ?? "Village"}",
                ObjectiveType = objectiveType,
                ObjectiveTarget = target,
                ObjectiveCount = count,
                RewardGold = goldReward,
                RewardDescription = $"{goldReward} gold coins",
                PlayerSerial = playerSer,
                GiverSerial = npcSer,
                SecondaryTarget = secondary,
                Destination = dest,
                DestinationMap = destMap
            };

            // Ask LLM to generate flavor text
            var identity = AIComponentRegistry.GetComponent(npc)?.Memory?.Identity;
            var identityPrompt = identity?.GetPersonalityPrompt() ?? "You are an NPC in Ultima Online.";

            var questPrompt = BuildQuestPrompt(identityPrompt, player.Name, quest);

            try
            {
                var reply = await LLMClient.ChatAsync("", questPrompt, AIConfig.ModelDialogue);
                if (!string.IsNullOrEmpty(reply))
                {
                    var parts = reply.Split('|');
                    if (parts.Length >= 2)
                    {
                        quest.QuestTitle = parts[0].Trim().Truncate(40);
                        quest.QuestDescription = parts[1].Trim().Truncate(160);
                    }
                    else
                    {
                        quest.QuestDescription = reply.Truncate(160);
                    }
                }
                else
                {
                    quest.QuestDescription = GetFallbackDescription(quest);
                }
            }
            catch
            {
                quest.QuestDescription = GetFallbackDescription(quest);
            }

            lock (ActiveQuests)
            {
                ActiveQuests[quest.QuestId] = quest;
            }

            // For Escort: spawn the escort NPC after quest is registered
            if (quest.ObjectiveType == QuestObjectiveType.Escort)
            {
                Timer.DelayCall(TimeSpan.FromSeconds(1), () => SpawnEscortNPC(quest, npc));
            }

            Console.WriteLine($"[AI QUEST] {npc.Name} -> {player.Name}: [{quest.ObjectiveType}] \"{quest.QuestDescription}\" (reward: {goldReward}g)");
            return quest;
        }

        private static void SpawnEscortNPC(AIQuest quest, BaseCreature giver)
        {
            try
            {
                // Create a simple escort NPC (using a generic BaseCreature)
                var escort = new BaseCreature(AIType.AI_Melee, FightMode.Closest, 10, 1, 0.2, 0.4)
                {
                    Name = "a nervous traveler",
                    Body = 0x190, // Human male
                    Hue = Utility.RandomSkinHue(),
                    ControlSlots = 0,
                    Tamable = false,
                    ControlMaster = null
                };

                // Place near giver
                var loc = new Point3D(giver.X + Utility.RandomMinMax(-2, 2), giver.Y + Utility.RandomMinMax(-2, 2), giver.Z);
                escort.MoveToWorld(loc, giver.Map);

                // Make them follow the player
                var player = World.FindMobile((Serial)(int)uint.Parse(quest.PlayerSerial));
                if (player != null)
                {
                    escort.ControlMaster = player;
                    escort.ControlTarget = player;
                    escort.ControlOrder = OrderType.Follow;
                }

                // Store reference on quest
                quest.EscortNpcSerial = escort.Serial;

                Console.WriteLine($"[AI QUEST] Spawned escort NPC for {quest.QuestId}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[AI QUEST] Escort spawn error: {ex.Message}");
            }
        }

        private static string BuildQuestPrompt(string identityPrompt, string playerName, AIQuest quest)
        {
            var basePrompt = $"{identityPrompt}\n\nGenerate a quest for {playerName}. ";

            string details;
            switch (quest.ObjectiveType)
            {
                case QuestObjectiveType.KillCount:
                    details = $"Ask them to kill {quest.ObjectiveCount} {quest.ObjectiveTarget}(s). Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.CollectItem:
                    details = $"Ask them to bring you {quest.ObjectiveCount} {quest.ObjectiveTarget}. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.DeliverItem:
                    details = $"Ask them to deliver {quest.ObjectiveCount} {quest.ObjectiveTarget} to {quest.SecondaryTarget}. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.Escort:
                    details = $"Ask them to escort someone to {quest.SecondaryTarget}. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.Explore:
                    details = $"Ask them to explore {quest.ObjectiveTarget} and report back. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.CombatBoss:
                    details = $"Ask them to slay the fearsome {quest.ObjectiveTarget}. Reward: {quest.RewardGold} gold. This is a dangerous bounty!";
                    break;
                case QuestObjectiveType.MerchantRun:
                    details = $"Ask them to purchase {quest.ObjectiveCount} {quest.ObjectiveTarget}(s) and deliver them to {quest.SecondaryTarget}. They'll need gold upfront. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.CraftItem:
                    details = $"Ask them to craft {quest.ObjectiveCount} {quest.ObjectiveTarget}(s) and bring them to you. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.NpcRelation:
                    details = $"Ask them to travel to {quest.ObjectiveTarget} and exchange pleasantries {quest.ObjectiveCount} times to build goodwill. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.GuardDuty:
                    details = $"Ask them to defend {quest.ObjectiveTarget} for {quest.ObjectiveCount} waves of attackers. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.Rescue:
                    details = $"Ask them to rescue {quest.ObjectiveTarget} from {quest.SecondaryTarget}. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.Scout:
                    details = $"Ask them to scout {quest.ObjectiveTarget} and report what they find. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.GatherResource:
                    details = $"Ask them to gather {quest.ObjectiveCount} units of {quest.ObjectiveTarget}. Reward: {quest.RewardGold} gold.";
                    break;
                case QuestObjectiveType.Bounty:
                    details = $"Post a bounty on {quest.ObjectiveTarget}. {quest.RewardGold} gold for the head of this villain!";
                    break;
                default:
                    details = "";
                    break;
            }

            return basePrompt + details +
                   $"\n\nOutput format: TITLE|DESCRIPTION\n" +
                   $"Title should be short. Description should be 1 sentence (max 160 chars) in your character's voice.";
        }

        private static string GetFallbackDescription(AIQuest quest)
        {
            switch (quest.ObjectiveType)
            {
                case QuestObjectiveType.KillCount:
                    return $"I need you to cull the {quest.ObjectiveTarget} population. Kill {quest.ObjectiveCount} of them.";
                case QuestObjectiveType.CollectItem:
                    return $"I need {quest.ObjectiveCount} {quest.ObjectiveTarget}. Bring them to me for a reward.";
                case QuestObjectiveType.DeliverItem:
                    return $"Take these {quest.ObjectiveCount} {quest.ObjectiveTarget} to {quest.SecondaryTarget}.";
                case QuestObjectiveType.Escort:
                    return $"Escort my friend to {quest.SecondaryTarget}. Keep them safe.";
                case QuestObjectiveType.Explore:
                    return $"Go to {quest.ObjectiveTarget} and tell me what you find.";
                case QuestObjectiveType.CombatBoss:
                    return $"The creature {quest.ObjectiveTarget} terrorizes our lands. Slay it and return for your reward of {quest.RewardGold} gold!";
                case QuestObjectiveType.MerchantRun:
                    return $"Purchase {quest.ObjectiveCount} {quest.ObjectiveTarget} and deliver them to {quest.SecondaryTarget}. I'll pay {quest.RewardGold} gold.";
                case QuestObjectiveType.CraftItem:
                    return $"Craft {quest.ObjectiveCount} {quest.ObjectiveTarget} and bring them to me. {quest.RewardGold} gold is your reward.";
                case QuestObjectiveType.NpcRelation:
                    return $"Travel to {quest.ObjectiveTarget} and speak with them {quest.ObjectiveCount} times to strengthen our ties.";
                case QuestObjectiveType.GuardDuty:
                    return $"Defend {quest.ObjectiveTarget} through {quest.ObjectiveCount} waves of attackers. I'll pay {quest.RewardGold} gold.";
                case QuestObjectiveType.Rescue:
                    return $"Rescue {quest.ObjectiveTarget} from {quest.SecondaryTarget}. Bring them back safely for {quest.RewardGold} gold.";
                case QuestObjectiveType.Scout:
                    return $"Scout {quest.ObjectiveTarget} and return with your report. {quest.RewardGold} gold for your trouble.";
                case QuestObjectiveType.GatherResource:
                    return $"I need {quest.ObjectiveCount} units of {quest.ObjectiveTarget}. Gather them and I'll pay {quest.RewardGold} gold.";
                case QuestObjectiveType.Bounty:
                    return $"A bounty of {quest.RewardGold} gold on {quest.ObjectiveTarget}. Bring me proof of its death.";
                default:
                    return "A task awaits.";
            }
        }

        /// <summary>Progress a kill-count quest. Called when player kills a matching creature.
        /// Also handles CombatBoss and Bounty quests.</summary>
        public static void ReportKill(Mobile player, BaseCreature killed)
        {
            var playerSer = player.Serial.Value.ToString();
            var killName = killed.Name?.ToLowerInvariant() ?? killed.GetType().Name.ToLowerInvariant();

            lock (ActiveQuests)
            {
                // Check KillCount quests
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.KillCount &&
                    q.ObjectiveTarget.ToLowerInvariant() == killName))
                {
                    quest.ObjectiveProgress++;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: {quest.ObjectiveProgress}/{quest.ObjectiveCount} {quest.ObjectiveTarget} killed.");

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Objective complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }

                // Check CombatBoss quests (boss name matches creature name or type)
                foreach (var quest in ActiveQuests.Values.Where(q2 =>
                    q2.PlayerSerial == playerSer &&
                    !q2.IsCompleted && !q2.IsExpired &&
                    q2.ObjectiveType == QuestObjectiveType.CombatBoss))
                {
                    var questTarget = quest.ObjectiveTarget.ToLowerInvariant();
                    if (killName.Contains(questTarget) || questTarget.Contains(killName))
                    {
                        quest.ObjectiveProgress++;
                        player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: {quest.ObjectiveTarget} slain!");

                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Boss slain! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }

                // Check Bounty quests
                foreach (var quest in ActiveQuests.Values.Where(q3 =>
                    q3.PlayerSerial == playerSer &&
                    !q3.IsCompleted && !q3.IsExpired &&
                    q3.ObjectiveType == QuestObjectiveType.Bounty))
                {
                    var questTarget = quest.ObjectiveTarget.ToLowerInvariant();
                    if (killName.Contains(questTarget) || questTarget.Contains(killName))
                    {
                        quest.ObjectiveProgress++;
                        player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Bounty collected on {quest.ObjectiveTarget}!");

                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Bounty complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }
            }
        }

        /// <summary>Progress a delivery quest. Called when player gives item to target NPC.</summary>
        public static void ReportDelivery(Mobile player, BaseCreature recipient, Item item)
        {
            if (item == null) return;
            var playerSer = player.Serial.Value.ToString();
            var recipientName = recipient.Name?.ToLowerInvariant() ?? "";

            lock (ActiveQuests)
            {
                // DeliverItem quests
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.DeliverItem &&
                    q.SecondaryTarget.ToLowerInvariant().Contains(recipientName)))
                {
                    quest.ObjectiveProgress++;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Delivered {item.Name} to {recipient.Name} ({quest.ObjectiveProgress}/{quest.ObjectiveCount}).");
                    item.Delete();

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Objective complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }

                // MerchantRun quests
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.MerchantRun &&
                    q.SecondaryTarget.ToLowerInvariant().Contains(recipientName)))
                {
                    var itemName = item.Name?.ToLowerInvariant() ?? item.GetType().Name.ToLowerInvariant();
                    if (quest.ObjectiveTarget.ToLowerInvariant().Contains(itemName))
                    {
                        quest.ObjectiveProgress++;
                        player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Delivered {item.Name} to {recipient.Name} ({quest.ObjectiveProgress}/{quest.ObjectiveCount}).");
                        item.Delete();

                        if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                        {
                            quest.IsCompleted = true;
                            player.SendMessage(0x44, "[Quest] Merchant run complete! Return to " + quest.GiverNpcName + " for your reward.");
                        }
                    }
                }
            }
        }

        /// <summary>Progress a crafting quest. Called when player crafts a matching item.</summary>
        public static void ReportCrafted(Mobile player, Item crafted)
        {
            if (crafted == null) return;
            var playerSer = player.Serial.Value.ToString();
            var itemName = crafted.Name?.ToLowerInvariant() ?? crafted.GetType().Name.ToLowerInvariant();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.CraftItem &&
                    q.ObjectiveTarget.ToLowerInvariant().Contains(itemName)))
                {
                    quest.ObjectiveProgress++;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Crafted {crafted.Name} ({quest.ObjectiveProgress}/{quest.ObjectiveCount}).");

                    crafted.Delete();

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Crafting complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }
            }
        }

        /// <summary>Progress a gather-resource quest. Called when player gathers resources.</summary>
        public static void ReportGathered(Mobile player, string resourceName, int amount)
        {
            if (string.IsNullOrEmpty(resourceName)) return;
            var playerSer = player.Serial.Value.ToString();
            var resName = resourceName.ToLowerInvariant();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.GatherResource &&
                    q.ObjectiveTarget.ToLowerInvariant().Contains(resName)))
                {
                    quest.ObjectiveProgress += amount;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Gathered {resourceName} ({quest.ObjectiveProgress}/{quest.ObjectiveCount}).");

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Gathering complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }
            }
        }

        /// <summary>Progress an NPC relation quest. Called when player talks to the target NPC.</summary>
        public static void ReportNpcRelation(Mobile player, string targetNpcName)
        {
            if (string.IsNullOrEmpty(targetNpcName)) return;
            var playerSer = player.Serial.Value.ToString();
            var targetName = targetNpcName.ToLowerInvariant();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.NpcRelation &&
                    q.ObjectiveTarget.ToLowerInvariant().Contains(targetName)))
                {
                    quest.ObjectiveProgress++;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Spoke with {targetNpcName} ({quest.ObjectiveProgress}/{quest.ObjectiveCount}).");

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Relations built! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }
            }
        }

        /// <summary>Progress a guard duty quest. Called when a wave is defended.</summary>
        public static void ReportGuardDutyProgress(Mobile player)
        {
            var playerSer = player.Serial.Value.ToString();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.GuardDuty))
                {
                    quest.ObjectiveProgress++;
                    player.SendMessage(0x482, $"[Quest] {quest.QuestTitle}: Defended wave {quest.ObjectiveProgress}/{quest.ObjectiveCount}.");

                    if (quest.ObjectiveProgress >= quest.ObjectiveCount)
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Guard duty complete! Return to " + quest.GiverNpcName + " for your reward.");
                    }
                }
            }
        }

        /// <summary>Progress a scout quest. Called when player reaches the scout destination.</summary>
        public static void ReportScoutComplete(Mobile player)
        {
            var playerSer = player.Serial.Value.ToString();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.Scout))
                {
                    quest.IsCompleted = true;
                    player.SendMessage(0x44, "[Quest] Scouting complete! Return to " + quest.GiverNpcName + " to report your findings.");
                }
            }
        }

        /// <summary>Progress an escort quest. Called periodically when escort NPC is near destination.</summary>
        public static void ReportEscortProgress(Mobile player, BaseCreature escortNpc)
        {
            var playerSer = player.Serial.Value.ToString();

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.Escort &&
                    q.EscortNpcSerial == escortNpc.Serial))
                {
                    if (quest.Destination != Point3D.Zero && escortNpc.InRange(quest.Destination, 5))
                    {
                        quest.IsCompleted = true;
                        player.SendMessage(0x44, "[Quest] Escort complete! " + escortNpc.Name + " reached " + quest.SecondaryTarget + ". Return to " + quest.GiverNpcName + " for reward.");
                        escortNpc.Delete(); // Escort NPC leaves
                    }
                }
            }
        }

        /// <summary>Progress an explore quest. Called when player enters the target region.</summary>
        public static void ReportExplore(Mobile player, Region region)
        {
            if (region == null) return;
            var playerSer = player.Serial.Value.ToString();
            var regionName = region.Name?.ToLowerInvariant() ?? "";

            lock (ActiveQuests)
            {
                foreach (var quest in ActiveQuests.Values.Where(q =>
                    q.PlayerSerial == playerSer &&
                    !q.IsCompleted && !q.IsExpired &&
                    q.ObjectiveType == QuestObjectiveType.Explore &&
                    q.ObjectiveTarget.ToLowerInvariant().Contains(regionName)))
                {
                    quest.IsCompleted = true;
                    player.SendMessage(0x44, "[Quest] Exploration complete! You've reached " + quest.ObjectiveTarget + ". Return to " + quest.GiverNpcName + " for reward.");
                }
            }
        }

        /// <summary>Complete a quest and give rewards.</summary>
        public static bool CompleteQuest(Mobile player, BaseCreature npc)
        {
            var playerSer = player.Serial.Value.ToString();
            var npcSer = npc.Serial.Value.ToString();

            AIQuest quest = null;
            lock (ActiveQuests)
            {
                quest = ActiveQuests.Values.FirstOrDefault(q =>
                    q.PlayerSerial == playerSer &&
                    q.GiverSerial == npcSer &&
                    q.IsCompleted && !q.IsExpired);
            }

            if (quest == null)
            {
                player.SendMessage("You have no completed quests for " + (npc.Name ?? "this NPC") + ".");
                return false;
            }

            // Give reward
            if (quest.RewardGold > 0)
            {
                var gold = new Gold(quest.RewardGold);
                if (player.Backpack != null && player.Backpack.TryDropItem(player, gold, false))
                {
                    player.SendMessage(0x44, $"[Quest] Reward received: {quest.RewardGold} gold!");
                }
                else
                {
                    // Drop at feet
                    gold.MoveToWorld(player.Location, player.Map);
                    player.SendMessage(0x44, $"[Quest] Reward dropped at your feet: {quest.RewardGold} gold.");
                }
            }

            // Track completion
            lock (CompletedQuestIds)
            {
                CompletedQuestIds.Add(quest.QuestId);
            }

            // Remove from active
            lock (ActiveQuests)
            {
                ActiveQuests.Remove(quest.QuestId);
            }

            // Record in NPC memory
            var component = AIComponentRegistry.GetComponent(npc);
            component?.Memory?.RecordHelp(playerSer, player.Name);

            // Apply faction reputation for quest completion
            FactionReputationSystem.OnQuestCompleted(player, npc);

            Console.WriteLine($"[AI QUEST] {player.Name} completed quest: {quest.QuestTitle}");
            return true;
        }

        /// <summary>Get quest status string for an NPC.</summary>
        public static string GetQuestContext(Mobile player, BaseCreature npc)
        {
            var playerSer = player.Serial.Value.ToString();
            var npcSer = npc.Serial.Value.ToString();

            lock (ActiveQuests)
            {
                var quest = ActiveQuests.Values.FirstOrDefault(q =>
                    q.PlayerSerial == playerSer &&
                    q.GiverSerial == npcSer &&
                    !q.IsExpired);

                if (quest == null)
                    return "";

                if (quest.IsCompleted)
                    return $"\n\nIMPORTANT: {player.Name} completed the quest '{quest.QuestTitle}'. Thank them and offer the reward.";

                return $"\n\nCurrent quest for {player.Name}: {quest.QuestDescription} (Progress: {quest.ObjectiveProgress}/{quest.ObjectiveCount})";
            }
        }

        private static void CleanupExpired()
        {
            lock (ActiveQuests)
            {
                var expired = ActiveQuests.Values.Where(q => q.IsExpired).ToList();
                foreach (var q in expired)
                {
                    ActiveQuests.Remove(q.QuestId);
                    Console.WriteLine($"[AI QUEST] Expired: {q.QuestTitle} for player {q.PlayerSerial}");
                }
            }
        }
    }

    /// <summary>
    /// Hooks into creature kill events to progress kill-count quests.
    /// </summary>
    public static class QuestCombatHook
    {
        public static void Initialize()
        {
            EventSink.CreatureDeath += OnCreatureDeath;
        }

        private static void OnCreatureDeath(CreatureDeathEventArgs e)
        {
            if (e.Killer?.Player != true) return;
            if (!(e.Creature is BaseCreature bc)) return;

            AIQuestManager.ReportKill(e.Killer, bc);
        }
    }

    /// <summary>
    /// Hooks for explore quests - when player enters a new region.
    /// </summary>
    public static class QuestExploreHook
    {
        public static void Initialize()
        {
            EventSink.Movement += OnMovement;
        }

        private static void OnMovement(MovementEventArgs e)
        {
            if (e.Mobile?.Player != true) return;

            var region = Region.Find(e.Mobile.Location, e.Mobile.Map);
            var oldRegion = Region.Find(new Point3D(e.Mobile.X - GetDirectionOffset(e.Direction).X,
                e.Mobile.Y - GetDirectionOffset(e.Direction).Y, e.Mobile.Z), e.Mobile.Map);

            if (region != oldRegion && region != null)
            {
                AIQuestManager.ReportExplore(e.Mobile, region);
            }
        }

        private static Point3D GetDirectionOffset(Direction dir)
        {
            int x = 0, y = 0;
            Server.Movement.Movement.Offset(dir, ref x, ref y);
            return new Point3D(x, y, 0);
        }
    }

    /// <summary>
    /// Extension helper for string truncation.
    /// </summary>
    public static class StringExtensions
    {
        public static string Truncate(this string value, int maxLength)
        {
            if (string.IsNullOrEmpty(value)) return value;
            return value.Length <= maxLength ? value : value.Substring(0, maxLength);
        }
    }
}
