using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Server;
using Server.Items;
using Server.Mobiles;
using Server.Network;

namespace Server.AIOrchestrator.Subagents
{
    /// <summary>
    /// AI-driven Economy Subagent.
    /// Uses an LLM model to generate dynamic economic events instead of static counters.
    /// Runs on a timer, gathers world state, calls the model, and applies economic changes.
    /// </summary>
    public static class EconomySubagent
    {
        private static Timer _timer;
        private static DateTime _lastEvent = DateTime.MinValue;
        private const int EconomyIntervalMinutes = 15;

        // Tracked economic state
        private static Dictionary<string, int> _killCounts = new Dictionary<string, int>();
        private static Dictionary<string, int> _harvestCounts = new Dictionary<string, int>();
        private static Dictionary<string, double> _priceModifiers = new Dictionary<string, double>();

        // Active economic events generated by the AI
        private static List<EconomyEvent> _activeEvents = new List<EconomyEvent>();

        public static void Initialize()
        {
            _timer = Timer.DelayCall(TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(EconomyIntervalMinutes), EconomyTick);
            Console.WriteLine("[AIOrchestrator] AI Economy Subagent initialized (every " + EconomyIntervalMinutes + " min).");
        }

        /// <summary>Record a creature kill for economic tracking.</summary>
        public static void RecordKill(string creatureName)
        {
            if (string.IsNullOrEmpty(creatureName)) return;
            lock (_killCounts)
            {
                var key = creatureName.ToLowerInvariant();
                if (!_killCounts.ContainsKey(key))
                    _killCounts[key] = 0;
                _killCounts[key]++;
            }
        }

        /// <summary>Record a resource harvest for economic tracking.</summary>
        public static void RecordHarvest(string itemName)
        {
            if (string.IsNullOrEmpty(itemName)) return;
            lock (_harvestCounts)
            {
                var key = itemName.ToLowerInvariant();
                if (!_harvestCounts.ContainsKey(key))
                    _harvestCounts[key] = 0;
                _harvestCounts[key]++;
            }
        }

        /// <summary>Get a price modifier for a specific item/vendor type (1.0 = normal).</summary>
        public static double GetPriceModifier(string key)
        {
            lock (_priceModifiers)
            {
                double mod;
                if (_priceModifiers.TryGetValue(key.ToLowerInvariant(), out mod))
                    return mod;
            }
            return 1.0;
        }

        /// <summary>Get the current economy context string for NPC dialogue.</summary>
        public static string GetEconomyContext()
        {
            lock (_activeEvents)
            {
                if (_activeEvents.Count == 0)
                    return "The economy is stable. Trade continues as usual.";

                var sb = new System.Text.StringBuilder();
                sb.AppendLine("Current economic conditions (market rumors):");
                foreach (var evt in _activeEvents)
                {
                    sb.AppendLine("- " + evt.Description);
                }
                return sb.ToString();
            }
        }

        private static void EconomyTick()
        {
            try
            {
                if (!AIConfig.Enabled) return;

                var worldState = BuildWorldState();
                if (string.IsNullOrEmpty(worldState)) return;

                // Call LLM asynchronously
                Task.Run(async () =>
                {
                    try
                    {
                        var result = await GenerateEconomyEvent(worldState);
                        if (!string.IsNullOrEmpty(result))
                        {
                            ApplyEconomyEvent(result);
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("[AI Economy] Generation error: " + ex.Message);
                    }
                });

                _lastEvent = DateTime.UtcNow;
            }
            catch (Exception ex)
            {
                Console.WriteLine("[AI Economy] Tick error: " + ex.Message);
            }
        }

        private static string BuildWorldState()
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("Current economic state of Britannia:");

            // Player count
            int playerCount = 0;
            foreach (var ns in NetState.Instances)
            {
                if (ns.Mobile?.Player == true)
                    playerCount++;
            }
            sb.AppendLine("- Active adventurers: " + playerCount);

            // Kill counts (top 5)
            lock (_killCounts)
            {
                var topKills = _killCounts.OrderByDescending(k => k.Value).Take(5).ToList();
                if (topKills.Count > 0)
                {
                    sb.AppendLine("- Most hunted creatures:");
                    foreach (var kvp in topKills)
                        sb.AppendLine("  * " + kvp.Key + ": " + kvp.Value + " killed recently");
                }
            }

            // Harvest counts (top 5)
            lock (_harvestCounts)
            {
                var topHarvest = _harvestCounts.OrderByDescending(k => k.Value).Take(5).ToList();
                if (topHarvest.Count > 0)
                {
                    sb.AppendLine("- Most harvested resources:");
                    foreach (var kvp in topHarvest)
                        sb.AppendLine("  * " + kvp.Key + ": " + kvp.Value + " units gathered");
                }
            }

            // Active events
            lock (_activeEvents)
            {
                if (_activeEvents.Count > 0)
                {
                    sb.AppendLine("- Current economic events:");
                    foreach (var evt in _activeEvents)
                        sb.AppendLine("  * " + evt.Description + " (duration: " + evt.RemainingMinutes + " min)");
                }
            }

            return sb.ToString();
        }

        private static async Task<string> GenerateEconomyEvent(string worldState)
        {
            string prompt = "You are the Economy God of Ultima Online. You control supply, demand, prices, and trade.\n\n" +
                            worldState +
                            "\n\nGenerate a SHORT economic event (1-2 sentences, max 200 chars) that changes prices or availability.\n" +
                            "Format: ITEM|REGION|CHANGE|DESCRIPTION\n" +
                            "ITEM: the affected item type (ore, wood, reagents, weapons, armor, gems, grain, fish, leather, cloth, potions, pets, scrolls, all)\n" +
                            "REGION: the affected region (Britain, Trinsic, Moonglow, Minoc, Yew, Jhelom, Skara Brae, Vesper, Nujel'm, Serpent's Hold, all)\n" +
                            "CHANGE: a number from -50 to +50 (percentage price change, negative = cheaper, positive = more expensive)\n" +
                            "DESCRIPTION: what happened (the narrative reason)\n\n" +
                            "Examples:\n" +
                            "ore|Minoc|+25|The Minoc mine collapsed! Iron ingot prices surged 25%.\n" +
                            "reagents|Moonglow|-15|A bountiful harvest of nightshade has flooded the Moonglow market. Reagent prices down 15%.\n" +
                            "weapons|Britain|+30|The orc raids have the Britain armory stretched thin. Weapon prices rose 30%.\n" +
                            "all|all|+5|The King announced a new tax. All prices up 5%.\n\n" +
                            "Output ONLY the pipe-delimited line. Nothing else.";

            try
            {
                return await LLMClient.ChatAsync("", prompt, AIConfig.ModelEconomy);
            }
            catch
            {
                return null;
            }
        }

        private static void ApplyEconomyEvent(string eventText)
        {
            if (string.IsNullOrEmpty(eventText)) return;

            // Parse: ITEM|REGION|CHANGE|DESCRIPTION
            var parts = eventText.Split('|');
            if (parts.Length < 4) return;

            var item = parts[0].Trim().ToLowerInvariant();
            var region = parts[1].Trim().ToLowerInvariant();
            int change;
            if (!int.TryParse(parts[2].Trim(), out change))
                return;
            var description = parts[3].Trim();

            // Clamp change
            change = Math.Max(-50, Math.Min(50, change));

            // Apply price modifier
            var key = item + "|" + region;
            lock (_priceModifiers)
            {
                double currentMod;
                if (!_priceModifiers.TryGetValue(key, out currentMod))
                    currentMod = 1.0;
                _priceModifiers[key] = currentMod + (change / 100.0);
            }

            // Create active event
            var evt = new EconomyEvent
            {
                Item = item,
                Region = region,
                Change = change,
                Description = description,
                CreatedAt = DateTime.UtcNow,
                DurationMinutes = 60 + Utility.Random(120) // 1-3 hours
            };

            lock (_activeEvents)
            {
                _activeEvents.Add(evt);
                if (_activeEvents.Count > 10)
                    _activeEvents.RemoveAt(0);
            }

            // Broadcast if significant
            if (Math.Abs(change) >= 20)
            {
                var hue = change > 0 ? 0x44 : 0x22; // Blue for price up, Red for price down
                BroadcastToAll("[Economy] " + description, hue);
            }

            Console.WriteLine("[AI Economy] Event: " + description + " (" + change + "%)");
        }

        /// <summary>Clean up expired events every tick.</summary>
        private static void CleanupExpiredEvents()
        {
            lock (_activeEvents)
            {
                _activeEvents.RemoveAll(e => e.IsExpired);
            }
        }

        private static void BroadcastToAll(string message, int hue)
        {
            foreach (var ns in NetState.Instances)
            {
                if (ns.Mobile != null)
                    ns.Mobile.SendMessage(hue, message);
            }
        }

        private class EconomyEvent
        {
            public string Item;
            public string Region;
            public int Change;
            public string Description;
            public DateTime CreatedAt;
            public int DurationMinutes;

            public bool IsExpired
            {
                get { return (DateTime.UtcNow - CreatedAt).TotalMinutes > DurationMinutes; }
            }

            public int RemainingMinutes
            {
                get { return Math.Max(0, DurationMinutes - (int)(DateTime.UtcNow - CreatedAt).TotalMinutes); }
            }
        }
    }

    /// <summary>Hooks to feed data into the economy system.</summary>
    public static class EconomyDataHook2
    {
        public static void Initialize()
        {
            EventSink.CreatureDeath += OnCreatureDeath;
            Console.WriteLine("[AIOrchestrator] Economy data hooks v2 registered.");
        }

        private static void OnCreatureDeath(CreatureDeathEventArgs e)
        {
            if (e.Creature != null)
            {
                EconomySubagent.RecordKill(e.Creature.Name ?? e.Creature.GetType().Name);
            }
        }
    }
}
